### ISSUE TITLE
欢迎 -> 教室使用指南 -> 7.课程详情和相关资源

### ISSUE THREAD

**Issue by Xiankai-Wan** [udacity/band-issues-cn#1]
## 截图
![0](https://user-images.githubusercontent.com/25104361/43691314-45dfe5f6-994d-11e8-9a86-0f20ce56d649.png)

## 具体描述
此处视频中关于课程资源中演示了一对一的部分，但是之后的课程并不是对所有学员开放一对一，这里建议底部加一些文字说明，不然部分学员不清楚规则。

**Comment by evestorm** [comment]
@Xiankai-Wan 已对 “教室使用指南” 进行了更新，你可以再快速过一遍~
