### ISSUE TITLE
描述统计学 I > 20 大小写

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#10]
## 课程导航+地址
描述统计学 I > [20 大小写](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/e37a7e2f-d479-4962-a366-cdcdf8aee7f6/modules/172d7273-794a-498c-a908-6803cfc7d6b6/lessons/7c28a383-f50b-4a62-bbc1-fa6b2b52504a/concepts/0d1fdcb2-f2f7-4680-87b3-b73238b9b126)

## 截图
![screen shot 2018-08-06 at 11 36 56 pm](https://user-images.githubusercontent.com/6949550/43726453-c4baf0e4-99d1-11e8-811f-c00129e7d548.png)

## 具体描述

高亮那句话好像不太通顺，括号也没有成对。

**Comment by evestorm** [comment]
已修复
