### ISSUE TITLE
设计 -> 15. 形状、大小与其他工具

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#100]
## 课程导航+地址
设计 -> [15. 形状、大小与其他工具
](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/3170e950-5743-4dbb-875f-6da4a3ed30f1/concepts/fbc5f08a-5996-4c22-9136-9e363847260f)

## 截图
![screen shot 2018-09-03 at 12 53 44 am](https://user-images.githubusercontent.com/6949550/44958513-fb4a7380-af13-11e8-8421-165cb907d952.png)

## 具体描述
1. “正如我们这里颜色的那样” 这句话看起来不怎么通顺呢，不知原文是怎样的；
2. 查了下 [ggplot2  的维基百科词条](https://zh.wikipedia.org/zh-cn/Ggplot2)，说“ggplot2是统计编程语言R的一个数据可视化绘图包“，不知与这里所说的 ”ggplot2 是....数据库“ 是不是有点冲突。

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
