### ISSUE TITLE
设计 -> 16. 通用设计提示

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#101]
## 课程导航+地址
设计 -> [16. 通用设计提示](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/3170e950-5743-4dbb-875f-6da4a3ed30f1/concepts/cb5de6a9-896f-4046-8d98-f98c6e21c153)

## 截图
![screen shot 2018-09-03 at 1 01 52 am](https://user-images.githubusercontent.com/6949550/44958600-179ae000-af15-11e8-9d00-03381e0752df.png)

## 具体描述
箭头标记的地方似乎缺少了标点符号。

**Comment by Kyliewang** [comment]
done
