### ISSUE TITLE
设计 -> 17. 良好可视化

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#102]
## 课程导航+地址
设计 -> [17. 良好可视化](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/3170e950-5743-4dbb-875f-6da4a3ed30f1/concepts/52cd369e-ecc9-41e7-bdcf-c4e004a9de6a)

## 截图
![screen shot 2018-09-03 at 1 05 52 am](https://user-images.githubusercontent.com/6949550/44958631-a4de3480-af15-11e8-953f-28206dc7d5de.png)

## 具体描述
Markdown 语法有点问题。

**Comment by sylviasun916** [comment]
fixed and thanks!
