### ISSUE TITLE
设计 -> 21. 复习

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#104]
## 课程导航+地址
设计 -> [21. 复习](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/3170e950-5743-4dbb-875f-6da4a3ed30f1/concepts/77cc36be-0fe3-43e9-bb2d-a698794882e7)

## 截图
![screen shot 2018-09-03 at 1 15 36 am](https://user-images.githubusercontent.com/6949550/44958756-25516500-af17-11e8-8364-b750772b254a.png)

## 具体描述
Markdown 语法有点问题。

**Comment by sylviasun916** [comment]
fixed and thanks
