### ISSUE TITLE
数据可视化简介 > 识别数据类型

### ISSUE THREAD

**Issue by PoBlue** [udacity/band-issues-cn#105]
## 课程导航+地址
[数据可视化简介 > 识别数据类型](
https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/ce38115a-28de-47a2-8ced-eb37bb2a39f3/concepts/f027575f-9582-44de-80d5-9579564065c6)

## 截图
<img width="713" alt="2018-09-03 12 16 06" src="https://user-images.githubusercontent.com/9304701/44967337-29ab6b80-af73-11e8-84c4-ef58ff28ea75.png">

## 具体描述
直接写上 `序数` 就行了, 不用在前面加个 ordinal（序数）

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
