### ISSUE TITLE
Tableau 中的数据可视化视图 -> 6. 文本：连接数据回顾

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#107]
## 课程导航+地址
Tableau 中的数据可视化视图 ->[ 6. 文本：连接数据回顾](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/6ae40236-0ca9-4ee2-80b7-ad715049a9ea/concepts/497ebaaa-0a76-4aec-a259-e4adfae923dd)

## 截图
![screen shot 2018-09-03 at 9 23 45 pm](https://user-images.githubusercontent.com/6949550/44989315-078c0a80-afc0-11e8-9b95-dc5bb801f114.png)

## 具体描述
两段话重复了。

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
