### ISSUE TITLE
用数据分析解决问题 > 分析问题解决框架 > 6. 分析与建模

### ISSUE THREAD

**Issue by molock** [udacity/band-issues-cn#11]
## 课程导航+地址
用数据分析解决问题 > 分析问题解决框架 > [6. 分析与建模](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/23f15771-2196-4410-90b8-6661c3694682/modules/8f120816-9158-4429-8c7d-032a66dc6b22/lessons/dd7bf461-dfec-484c-b932-d09744913c98/concepts/6b45c53a-baef-495f-a71f-d77c665e4e91)

## 截图
<img width="1212" alt="demo" src="https://i.loli.net/2018/08/06/5b686ea826ac3.png">

## 具体描述
视频22s处字幕 **让我们用关于电力的例子在这一步上做详细的说明** ，可以改为更符合汉语习惯的 **让我们以电力需求为例，在此做详细的说明**

**Comment by evestorm** [comment]
👍
