### ISSUE TITLE
Tableau 中的数据可视化视图 -> 14.练习：工作表

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#110]
## 课程导航+地址
Tableau 中的数据可视化视图 -> [14.练习：工作表](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/6ae40236-0ca9-4ee2-80b7-ad715049a9ea/concepts/751e6658-e19c-494e-b3f4-c32077b919c1)

## 截图
![screen shot 2018-09-04 at 11 13 30 pm](https://user-images.githubusercontent.com/6949550/45040299-45f4f880-b098-11e8-8ff8-279c7d4667d0.png)

## 具体描述
Markdown 语法似乎有点问题。

**Comment by sylviasun916** [comment]
fixed and thanks!
