### ISSUE TITLE
Tableau 中的数据可视化视图 -> 18. 练习：聚合

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#111]
## 课程导航+地址
Tableau 中的数据可视化视图 -> [18. 练习：聚合](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/6ae40236-0ca9-4ee2-80b7-ad715049a9ea/concepts/7c809c72-bcc7-4c24-bbf7-2f49307750df)

## 截图
![screen shot 2018-09-04 at 11 58 52 pm](https://user-images.githubusercontent.com/6949550/45042985-9bcc9f00-b09e-11e8-8d08-79bb9d89a026.png)

## 具体描述
Markdown 语法似乎有点问题。

**Comment by sylviasun916** [comment]
fixed and thanks!
