### ISSUE TITLE
Tableau 中的数据可视化视图 -> 21. 练习：层级

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#112]
## 课程导航+地址
Tableau 中的数据可视化视图 -> [21. 练习：层级](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/6ae40236-0ca9-4ee2-80b7-ad715049a9ea/concepts/8e70f8a9-4949-4ae5-8d79-b0c22ae6e4ab)

## 截图
![screen shot 2018-09-05 at 12 24 22 am](https://user-images.githubusercontent.com/6949550/45044504-e18b6680-b0a2-11e8-9751-cc1f93921713.png)

## 具体描述
- 箭头处的 Markdown 语法有点问题；
- 红框里的文字应该是”订单“。

**Comment by sylviasun916** [comment]
已修改 感谢反馈
