### ISSUE TITLE
数据可视化简介 > 问题是什么？

### ISSUE THREAD

**Issue by PoBlue** [udacity/band-issues-cn#113]
## 课程导航+地址
[数据可视化简介 > 问题是什么？](
https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/ce38115a-28de-47a2-8ced-eb37bb2a39f3/concepts/4cd30421-18ac-488c-b2e6-d6b842a4a400)

## 截图
<img width="875" alt="2018-09-05 10 37 37" src="https://user-images.githubusercontent.com/9304701/45067944-dadb0e80-b0f7-11e8-9314-1e202df57a0a.png">

## 具体描述
`这里` 是墙外链接

**Comment by Kyliewang** [comment]
Done
