### ISSUE TITLE
数据可视化简介 > 如果有两个以上变量 该怎么办呢？

### ISSUE THREAD

**Issue by PoBlue** [udacity/band-issues-cn#114]
## 课程导航+地址
[数据可视化简介 > 如果有两个以上变量 该怎么办呢？](
https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/ce38115a-28de-47a2-8ced-eb37bb2a39f3/concepts/2c42d764-c596-4d11-b0ae-a51423bd6265)

## 截图
<img width="862" alt="2018-09-05 10 34 17" src="https://user-images.githubusercontent.com/9304701/45067988-0b22ad00-b0f8-11e8-9404-58847ff6043e.png">

## 具体描述
视频00:11处

字幕：“散布图”

应改为：“散点图”

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
