### ISSUE TITLE
Tableau 中的数据可视化视图 ->24. 练习：标记和过滤I

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#116]
## 课程导航+地址
Tableau 中的数据可视化视图 -> [24. 练习：标记和过滤I
](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/6ae40236-0ca9-4ee2-80b7-ad715049a9ea/concepts/ae29c609-7828-46b4-91a8-183531874fda)

## 截图
![screen shot 2018-09-05 at 11 10 24 pm](https://user-images.githubusercontent.com/6949550/45102873-2d9ce080-b161-11e8-8ac7-f7bed113d8aa.png)

## 具体描述
Markdown 语法有点问题。

**Comment by sylviasun916** [comment]
fixed and thanks!
