### ISSUE TITLE
Tableau 中的数据可视化视图 -> 24. 练习：标记和过滤I

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#117]
## 课程导航+地址
Tableau 中的数据可视化视图 -> [24. 练习：标记和过滤I
](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/6ae40236-0ca9-4ee2-80b7-ad715049a9ea/concepts/ae29c609-7828-46b4-91a8-183531874fda)

## 截图
图一 
![screen shot 2018-09-05 at 11 13 46 pm](https://user-images.githubusercontent.com/6949550/45102961-676de700-b161-11e8-916c-b3416ff83059.png)

图二
<img width="393" alt="screen shot 2018-09-05 at 11 13 58 pm" src="https://user-images.githubusercontent.com/6949550/45102980-6dfc5e80-b161-11e8-8047-85842d6e5f76.png">

## 具体描述
这个练习题第三个选项我得到的结果是 `-500`（图二），而答案是 `500`（图一）。不知是不是我理解错了。

**Comment by Kyliewang** [comment]
已经修改。
