### ISSUE TITLE
Tableau 中的数据可视化视图 ->26. 练习：标记和过滤器 II

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#118]
## 课程导航+地址
Tableau 中的数据可视化视图 ->[26. 练习：标记和过滤器 II](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/6ae40236-0ca9-4ee2-80b7-ad715049a9ea/concepts/c071f2ac-6717-48b5-b80f-1c8d4c673c23)

## 截图
图一
![screen shot 2018-09-05 at 11 33 56 pm](https://user-images.githubusercontent.com/6949550/45104284-58d4ff00-b164-11e8-8bd6-48e72a0cdb16.png)

图二
![screen shot 2018-09-05 at 11 37 18 pm](https://user-images.githubusercontent.com/6949550/45104432-afdad400-b164-11e8-9a5b-373f818d9ca0.png)

## 具体描述
箭头哪里“下钻到每月级别“，之前课程里更多用的是”向下钻取到 ... 层级“（图二），有点不统一。

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
