### ISSUE TITLE
Tableau 中的数据可视化视图 ->27. 视频: Show Me

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#119]
## 课程导航+地址
Tableau 中的数据可视化视图 ->[27. 视频: Show Me
](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/6ae40236-0ca9-4ee2-80b7-ad715049a9ea/concepts/c7c17ca8-da6d-4c76-93c6-8aabde074602)
## 截图
![screen shot 2018-09-06 at 12 03 26 am](https://user-images.githubusercontent.com/6949550/45106090-5e344880-b168-11e8-89bf-7cfbf920332c.png)

## 具体描述
字幕看起来翻错了，应该是：你可以摁住 Command 按键或者 Control 按键。

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
