### ISSUE TITLE
描述统计学1 > 集中趋势测量

### ISSUE THREAD

**Issue by baizhenhui** [udacity/band-issues-cn#12]
## 截图
![image](https://user-images.githubusercontent.com/36567451/43758908-2b49f25a-9a50-11e8-858c-d52eea19bb10.png)

## 具体描述
对均值计算方式的描述有歧义，```数据集中的值数```可以用```数据集中所有测量值的个数```代替。

**Comment by evestorm** [comment]
@baizhenhui 非常细心，赞！
