### ISSUE TITLE
Tableau 中的数据可视化视图 ->28. 文本: Show Me

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#121]
## 课程导航+地址
Tableau 中的数据可视化视图 ->[28. 文本: Show Me](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/6ae40236-0ca9-4ee2-80b7-ad715049a9ea/concepts/ba7bc21c-4228-4575-92b5-6a3b17a3544b)

## 截图
![screen shot 2018-09-06 at 12 14 07 am](https://user-images.githubusercontent.com/6949550/45106709-eff08580-b169-11e8-8a95-3ed1887f3a0d.png)

## 具体描述
没猜错的话，和之前字幕里的问题一样。原意可能是：保持摁住 Command 按键或者 Control 按键（取决于你的操作系统）

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
