### ISSUE TITLE
课程跳转遮罩标点冗余

### ISSUE THREAD

**Issue by DonaldDai** [udacity/band-issues-cn#122]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/ce38115a-28de-47a2-8ced-eb37bb2a39f3/concepts/5b4a43c7-52e3-48cd-a3f0-46e4ada4a78e

## 截图
![image](https://user-images.githubusercontent.com/14327519/45229117-99b14d00-b2f7-11e8-8d8e-1b877a2f1a55.png)

## 具体描述
多了个符号

**Comment by Kyliewang** [comment]
@ChengGoooo 麻烦谷歌定位下原因。

**Comment by Kyliewang** [comment]
问号已经删除

**Comment by ChengGoooo** [comment]
我们去掉了标题中的标点符号，显得更加自然和统一。

@sylviasun916 这里能不能考虑修改一下中文翻译的文本，后面 “需要 5” 的位置是一个倒计时。我们把“需要”改成“倒计时：”之类的？

**Comment by sylviasun916** [comment]
@ChengGoooo  在后台找不到翻译文本哦，我们导出的文本里也没有这个。不确定是什么问题。

**Comment by sylviasun916** [comment]
@caochenwei  你知道这个文本是在后台哪里吗？ 可能需要修改一下 classroom 的 string 哦，谢谢！

**Comment by caochenwei** [comment]
https://github.com/udacity/classroom-web/blob/master/src/locales/zh-cn.js

你们有这个 repo 权限么？

**Comment by caochenwei** [comment]
https://github.com/udacity/classroom-web/pull/3751
