### ISSUE TITLE
Tableau 中的数据可视化视图 -> 30. 视频：小倍数和双轴

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#123]
## 课程导航+地址
Tableau 中的数据可视化视图 -> [30. 视频：小倍数和双轴](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/6ae40236-0ca9-4ee2-80b7-ad715049a9ea/concepts/6880a687-b918-4577-be6a-89cccb364d4c)

## 截图

截图一
![screen shot 2018-09-08 at 4 32 56 pm](https://user-images.githubusercontent.com/6949550/45252170-f3138d80-b384-11e8-8589-565bdece16f3.png)

截图二
![screen shot 2018-09-08 at 4 37 24 pm](https://user-images.githubusercontent.com/6949550/45252208-8220a580-b385-11e8-9bec-7a6c1793b931.png)

## 具体描述
字幕“最短路径”对应的是“Small multiples”，应该翻译为“小倍数”。

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
