### ISSUE TITLE
数据可视化简介 > 数据面板简介

### ISSUE THREAD

**Issue by PoBlue** [udacity/band-issues-cn#124]
## 课程导航+地址
[数据可视化简介 > 数据面板简介](
https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/ce38115a-28de-47a2-8ced-eb37bb2a39f3/concepts/6719321b-ecaa-4342-bbed-63bd404408e4)

## 截图
<img width="1220" alt="2018-09-08 6 40 44" src="https://user-images.githubusercontent.com/9304701/45253247-b5b7fb80-b396-11e8-8241-3e28054e9b11.png">

## 具体描述
这里的视屏链接是 Youtube 的，需墙外才行。

**Comment by Kyliewang** [comment]
替换为vimeo链接~
