### ISSUE TITLE
Tableau 中的数据可视化视图 -> 31. 文本：小倍数和双轴

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#125]
## 课程导航+地址
Tableau 中的数据可视化视图 -> [31. 文本：小倍数和双轴](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/6ae40236-0ca9-4ee2-80b7-ad715049a9ea/concepts/d52c44d2-cc50-4845-a577-40f4ea4475ca)

## 截图
![screen shot 2018-09-08 at 9 35 44 pm](https://user-images.githubusercontent.com/6949550/45254720-6500cc80-b3af-11e8-9961-6a34a7400b26.png)

## 具体描述
Markdown 语法有点问题。

**Comment by sylviasun916** [comment]
fixed and thanks!
