### ISSUE TITLE
Tableau 中的数据可视化视图 -> 33. 练习：小倍数

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#126]
## 课程导航+地址
Tableau 中的数据可视化视图 -> [33. 练习：小倍数](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/6ae40236-0ca9-4ee2-80b7-ad715049a9ea/concepts/49bd36dd-5a07-40d7-b61a-49ecf84fe2dd)

## 截图
![screen shot 2018-09-08 at 9 47 36 pm](https://user-images.githubusercontent.com/6949550/45255196-dfcce600-b3b5-11e8-9fee-cb85a2c31c4c.png)

## 具体描述
- 箭头处的标点防护有点问题；
- 红框处，如果没理解错的话，对应的应该是 State，也就是 “州”，不是“状态”。

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
