### ISSUE TITLE
Tableau 中的数据可视化视图 -> 34. 练习：双轴

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#127]
## 课程导航+地址
Tableau 中的数据可视化视图 -> [34. 练习：双轴](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/6ae40236-0ca9-4ee2-80b7-ad715049a9ea/concepts/9f588d07-6f84-47b7-99d9-0f1d489e281e)

## 截图
![screen shot 2018-09-08 at 10 32 12 pm](https://user-images.githubusercontent.com/6949550/45255311-2d961e00-b3b7-11e8-8a6c-54281cd8442e.png)

## 具体描述
Markdown 语法有点问题。

**Comment by sylviasun916** [comment]
fixed and thanks!
