### ISSUE TITLE
设计 > 探索性与解释性分析

### ISSUE THREAD

**Issue by PoBlue** [udacity/band-issues-cn#128]
## 课程导航+地址
[设计 > 探索性与解释性分析](
https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/3170e950-5743-4dbb-875f-6da4a3ed30f1/concepts/87aa9106-ba97-412c-b092-a485f879a9fa)

## 截图
<img width="634" alt="2018-09-09 12 58 53" src="https://user-images.githubusercontent.com/9304701/45261226-3545d900-b430-11e8-84ab-2e943ef7f888.png">
<img width="540" alt="2018-09-09 12 56 18" src="https://user-images.githubusercontent.com/9304701/45261227-3545d900-b430-11e8-8a0b-2224710cd261.png">

## 具体描述
英文版和中文版的对比。中文的有点问题

修改建议：不用将加黑的 `or` 翻译为 `或`，直接 `exploratory` 直译过来就好了

**Comment by sylviasun916** [comment]
已修改 非常感谢反馈！
