### ISSUE TITLE
设计 > 练习：探索性与解释性

### ISSUE THREAD

**Issue by PoBlue** [udacity/band-issues-cn#129]
## 课程导航+地址
[设计 > 练习：探索性与解释性](
https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/3170e950-5743-4dbb-875f-6da4a3ed30f1/concepts/742285ff-5a7f-4ac3-8a2f-4b41fee58075)

## 截图
<img width="362" alt="2018-09-09 1 07 23" src="https://user-images.githubusercontent.com/9304701/45261277-67a40600-b431-11e8-8e3d-2244c35f5bfa.png">
<img width="736" alt="2018-09-09 1 09 56" src="https://user-images.githubusercontent.com/9304701/45261292-ab970b00-b431-11e8-8acb-e860ac7b7c6a.png">

## 具体描述

问题：中文全都是`解释性`了

建议：第 2 和第 5  个选项的答案应为 `探索性`

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
