### ISSUE TITLE
描述统计学2 > 什么是离散程度测量

### ISSUE THREAD

**Issue by baizhenhui** [udacity/band-issues-cn#13]
## 截图
![image](https://user-images.githubusercontent.com/36567451/43763898-8f08e23e-9a5e-11e8-8a76-4c2a9254b60e.png)
![image](https://user-images.githubusercontent.com/36567451/43764101-11bddc8e-9a5f-11e8-8c20-1f02ba7a8344.png)
![image](https://user-images.githubusercontent.com/36567451/43763949-b3f6e384-9a5e-11e8-8715-faa776786f10.png)

## 具体描述
这里应该使用`极值`或者此前练习中用的`全距`，就是`最大值-最小值`。

**Comment by evestorm** [comment]
mark：字幕问题收集>10后一并解决。
