### ISSUE TITLE
设计 > 可视化编码的专家之言

### ISSUE THREAD

**Issue by PoBlue** [udacity/band-issues-cn#131]
## 课程导航+地址
[设计 > 可视化编码的专家之言](
https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/3170e950-5743-4dbb-875f-6da4a3ed30f1/concepts/1a7c9ee5-41b1-43ad-ae15-18154e5151da)

## 截图
<img width="675" alt="2018-09-09 6 29 56" src="https://user-images.githubusercontent.com/9304701/45263588-6dfca700-b45e-11e8-8d55-ab9c4dbd4460.png">

## 具体描述
`要挣扎着` 应改为 `很难`

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
