### ISSUE TITLE
tableau 中数据可视化 > [4.文本：课程大纲回顾]

### ISSUE THREAD

**Issue by ZenRay** [udacity/band-issues-cn#134]
## 课程导航+地址
tableau 中数据可视化 > [4.文本：课程大纲回顾](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/6ae40236-0ca9-4ee2-80b7-ad715049a9ea/concepts/8c814e7f-5ef8-4bb2-a59b-d70f25e7a22f)

## 截图
![image](https://user-images.githubusercontent.com/24636410/45307584-f14af500-b551-11e8-9421-875dc152821f.png)

## 具体描述
这几个地址的链接均不可用，是网页变更了非 GFW 原因。

**Comment by Kyliewang** [comment]
Done
