### ISSUE TITLE
Tableau 中的数据可视化视图 > 视频：计算字段

### ISSUE THREAD

**Issue by PoBlue** [udacity/band-issues-cn#136]
## 课程导航+地址
[Tableau 中的数据可视化视图 > 视频：计算字段](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/6ae40236-0ca9-4ee2-80b7-ad715049a9ea/concepts/47e10fe8-697c-4e68-9680-e4ffc79b6cb9)

## 截图
![2018-10-12 11 30 17](https://user-images.githubusercontent.com/9304701/46846559-a05d4380-ce12-11e8-98ed-4d8e7f8e8f23.png)

## 具体描述

Markdown 问题：

- 1 处为斜体
- 2 处为链接

**Comment by yifangwang08** [comment]
已经修改了！感谢反馈！
