### ISSUE TITLE
在 Tableau 中创建面板和故事 > 文本：关于创建带Trina的数据面板的一般注意事项

### ISSUE THREAD

**Issue by PoBlue** [udacity/band-issues-cn#138]
## 课程导航+地址
[在 Tableau 中创建面板和故事 > 文本：关于创建带Trina的数据面板的一般注意事项](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/ea8da92d-8a92-4d06-9681-83138d5816e7/concepts/eaf0ab73-5a7e-446d-958d-a574fa01a9f5)

## 截图
![2018-10-12 12 04 53](https://user-images.githubusercontent.com/9304701/46847493-38f5c280-ce17-11e8-88a4-6ee7b11e05c7.png)

## 具体描述
如图的标记，是 markdown 的问题

**Comment by yifangwang08** [comment]
已经修改好了！感谢反馈！
