### ISSUE TITLE
外部链接失效 - SQL窗口功能【2.视频：窗口功能1】

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/band-issues-cn#143]
## 5. 技能方向 - 数据分析与SQL（二选一）> [选修]SQL窗口功能 > [2.视频：窗口功能1](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/5dedcb7b-7b19-4ef3-b19b-e7b555c75807/modules/4236eb8d-c10b-4538-855c-eb43bc3b2c84/lessons/a717e896-d9da-404c-8963-ae690279f2df/concepts/4c71795c-8ebf-4a3f-b951-494220b702cc)

![image](https://user-images.githubusercontent.com/7297350/49698116-a2693600-fbfa-11e8-88b8-ad5e03d6ea56.png)

![image](https://user-images.githubusercontent.com/7297350/49698125-b876f680-fbfa-11e8-92fb-3a43e44e1e81.png)

## 具体描述
红色框中的链接yi已失效，点击跳转到了“Page not found”页面

**Comment by yifangwang08** [comment]
感谢反馈！链接已更改！
