### ISSUE TITLE
翻译问题 + Markdown样式问题【20.视频：百分位数】

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/band-issues-cn#151]
## 5. 技能方向 - 数据分析与SQL（二选一）> [选修]SQL窗口功能 > [20.视频：百分位数](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/5dedcb7b-7b19-4ef3-b19b-e7b555c75807/modules/4236eb8d-c10b-4538-855c-eb43bc3b2c84/lessons/a717e896-d9da-404c-8963-ae690279f2df/concepts/92f9fbfc-b4e9-49ac-9ba0-c0359d6363d3)

![image](https://user-images.githubusercontent.com/7297350/49711519-ccfad380-fc7a-11e8-9458-9312b109fb20.png)

## 具体描述
1. bucket应该翻译为“分桶”而不是“水桶”
2. 红框位置Markdown样式损坏

**Comment by yifangwang08** [comment]
感谢反馈~
