### ISSUE TITLE
链接损坏 + Markdown样式损坏【4.解决方案：完全外部并集】

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/band-issues-cn#156]
## 5. 技能方向 - 数据分析与SQL（二选一）> [选修]SQL高级并集与性能优化 > [4.解决方案：完全外部并集](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/5dedcb7b-7b19-4ef3-b19b-e7b555c75807/modules/4236eb8d-c10b-4538-855c-eb43bc3b2c84/lessons/79e079c3-42c0-4413-843a-ddf3a261d1cf/concepts/01f6b128-2a97-47aa-ae16-7f59023de69e)

![image](https://user-images.githubusercontent.com/7297350/49712513-c884e980-fc7f-11e8-911d-f16e41cd62e6.png)

![image](https://user-images.githubusercontent.com/7297350/49712565-100b7580-fc80-11e8-8132-248c9f69b145.png)

## 具体描述
1. 链接的Markdown样式损坏
2. 直接点击跳转后进入“Page not found”页面

**Comment by yifangwang08** [comment]
感谢反馈！链接已更改~
