### ISSUE TITLE
数据分析与SQL > SQL子查询和临时表格 > 11. 视频：WITH > 翻译错误

### ISSUE THREAD

**Issue by leesper** [udacity/band-issues-cn#157]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd100-cn/parts/fb1232d2-1cfe-4bb0-8d6f-7bab75e9796c/modules/633ca2b0-b1b2-4821-89f8-60584b2a4a54/lessons/b50a9cfd-566a-4b42-bf4f-70081b557c0b/concepts/45018964-e64d-46a7-bd77-98bcae5854f1

## 截图
![image](https://user-images.githubusercontent.com/5260728/49713518-03891c00-fc84-11e8-808b-9b13d5915362.png)

## 具体描述
视频23s处中英文字幕错误，应该改为：
1. Let's say you've got a subquery that takes an hour to run
2. 假设运行一个子查询需要一个小时

**Comment by yifangwang08** [comment]
感谢反馈！方便的话希望下次提 issue 时可以把课程章节在标题里标注一下哦（教室的链接我们进去比较慢 :(
