### ISSUE TITLE
网站名称不应该翻译 + 链接失效【7.解决方案：带比较运算符的并集】

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/band-issues-cn#158]
## 5. 技能方向 - 数据分析与SQL（二选一）> [选修]SQL高级并集与性能优化 > [7.解决方案：带比较运算符的并集](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/5dedcb7b-7b19-4ef3-b19b-e7b555c75807/modules/4236eb8d-c10b-4538-855c-eb43bc3b2c84/lessons/79e079c3-42c0-4413-843a-ddf3a261d1cf/concepts/5bbe86f1-1814-4008-a4c5-a3b8457d78d7)

![image](https://user-images.githubusercontent.com/7297350/49733224-e7a16c80-fcbb-11e8-9392-063fa0f962f4.png)

![image](https://user-images.githubusercontent.com/7297350/49733324-20d9dc80-fcbc-11e8-81c5-15ceb41a13a9.png)

## 具体描述
1. Stackoverflow是一个网站名称，不应该翻译
2. 链接失效

**Comment by yifangwang08** [comment]
感谢反馈！
