### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by ketra21** [udacity/band-issues-cn#165]
## 课程导航+地址
例子：商业数据分析 > 4. 用数据分析解决商业问题 > PROJECT > [2. 项目详情](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/23f15771-2196-4410-90b8-6661c3694682/modules/645d58b0-0428-4f37-84b7-d23ab925e533/lessons/69611016-0e23-4c4d-a68b-c64329f24240/concepts/340c6317-9b46-4959-b222-a1cf85a9ad48)

## 截图
<img width="1212" alt="demo" src="图片地址">
![image](https://user-images.githubusercontent.com/38323732/49851870-695cdb80-fe1d-11e8-8ba3-8f79c066ba76.png)

## 具体描述

可以把英文的语法结构圆润翻一下，避免双重否定~~

原内容：除非这些新客户带来的预期利润超过一万美元，否则管理层不会向他们寄送产品目录册。
修改为：如果这些新客户带来的预期利润超过一万美元，那么管理层就会向他们寄送产品目录册。

**Comment by yifangwang08** [comment]
感谢反馈！
