### ISSUE TITLE
5. 技能方向 - 数据分析与 SQL（二选一） > 课程6. [选修] SQL窗口功能 > 2. 视频：窗口功能

### ISSUE THREAD

**Issue by xfzhu2003** [udacity/band-issues-cn#170]
## 课程导航+地址
5. 技能方向 - 数据分析与 SQL（二选一） > 课程6. [选修] SQL窗口功能 > [2. 视频：窗口功能1](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/5dedcb7b-7b19-4ef3-b19b-e7b555c75807/modules/4236eb8d-c10b-4538-855c-eb43bc3b2c84/lessons/a717e896-d9da-404c-8963-ae690279f2df/concepts/4c71795c-8ebf-4a3f-b951-494220b702cc)

## 截图
![image](https://user-images.githubusercontent.com/1688209/49862315-dfbb0700-fe38-11e8-9de9-5ec742b91769.png)

## 具体描述
这里中文字幕未翻译“window”这个单词，为保持一致，建议翻译成“窗口”

**Comment by yifangwang08** [comment]
感谢反馈！
