### ISSUE TITLE
翻译没有使用专业术语

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/band-issues-cn#172]
## 6. 业务方向 - 用Tableau创建可视化（二选一）> 数据可视化简介 > [4.更多驱动力](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/ce38115a-28de-47a2-8ced-eb37bb2a39f3/concepts/4e468460-2af9-4f32-a267-d8ac97ab88da)

![image](https://user-images.githubusercontent.com/7297350/49876190-cc6e6280-fe5d-11e8-829c-97c25bdaa0c8.png)

## 具体描述
视频9s处字幕“标准偏差”，需改为“标准差”，因为“standard deviation”翻译为“标准差”属于数学专业术语。

**Comment by yifangwang08** [comment]
感谢反馈！
