### ISSUE TITLE
描述统计学 > 描述统计学II > 4. 五数概括法简介 > 翻译错误

### ISSUE THREAD

**Issue by leesper** [udacity/band-issues-cn#174]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd100-cn/parts/e37a7e2f-d479-4962-a366-cdcdf8aee7f6/modules/990fa1c9-01d0-4a4c-8f52-21b371291643/lessons/ff38bd12-68b6-4ae9-971e-bbefe991a201/concepts/7d349d47-234d-4815-a46e-2363624ef3e0

## 截图
![image](https://user-images.githubusercontent.com/5260728/49906281-3150a980-feac-11e8-84fd-9a118dad0ef1.png)

## 具体描述
视频09s处字幕将range翻译为值域，需改为“极差”，2分44秒和2分48秒处也出现同样的翻译错误。

**Comment by yifangwang08** [comment]
感谢反馈！
