### ISSUE TITLE
描述统计学 II > 什么是离散程度测量？

### ISSUE THREAD

**Issue by Xiankai-Wan** [udacity/band-issues-cn#18]
## 课程导航+地址
描述统计学 II > [什么是离散程度测量？](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/e37a7e2f-d479-4962-a366-cdcdf8aee7f6/modules/172d7273-794a-498c-a908-6803cfc7d6b6/lessons/ff38bd12-68b6-4ae9-971e-bbefe991a201/concepts/3165d424-4154-41bc-b6d3-838da6aee551)

## 截图
![image](https://user-images.githubusercontent.com/25104361/43835203-a1199636-9b43-11e8-9788-bd01c773ef6e.png)

## 具体描述
这里统一为值域或者极差应该会更好。

**Comment by evestorm** [comment]
与 [此issue](https://github.com/udacity/band-issues-cn/issues/13) 重复
