### ISSUE TITLE
描述统计学 I > 16 练习 集中趋势测量（众数）

### ISSUE THREAD

**Issue by Xiankai-Wan** [udacity/band-issues-cn#2]
## 课程导航+地址
描述统计学 I > [16 练习 集中趋势测量（众数）](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/e37a7e2f-d479-4962-a366-cdcdf8aee7f6/modules/172d7273-794a-498c-a908-6803cfc7d6b6/lessons/7c28a383-f50b-4a62-bbc1-fa6b2b52504a/concepts/76e15c9d-1fbf-4bae-af5f-8294efbae67c)

## 截图
![image](https://user-images.githubusercontent.com/25104361/43720366-dc265016-99c2-11e8-913b-9a1b0ac26cf4.png)

## 具体描述
这里答案不够严谨，当数量为偶数时，中位数是中间两个数的平均数，这个数可能并不存在数据中，或者并不是中间位置。

**Comment by evestorm** [comment]
Awesome！
