### ISSUE TITLE
5. 技能方向 - 数据分析与 SQL（二选一） > 课程7. [选修] SQL高级并集与性能优化 > [14. 视频：性能优化的驱动力]

### ISSUE THREAD

**Issue by xfzhu2003** [udacity/band-issues-cn#202]
## 课程导航+地址
5. 技能方向 - 数据分析与 SQL（二选一） > 课程7. [选修] SQL高级并集与性能优化 > [14. 视频：性能优化的驱动力](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/5dedcb7b-7b19-4ef3-b19b-e7b555c75807/modules/4236eb8d-c10b-4538-855c-eb43bc3b2c84/lessons/79e079c3-42c0-4413-843a-ddf3a261d1cf/concepts/54177881-bd1b-4115-ab44-21d74349b1b2)

## 截图
4
00:00:07,845 --> 00:00:10,845
modern databases can scale to work with huge amounts of data
4
00:00:07,844 --> 00:00:10,844
现代数据库足够强大 可以处理大量数据

## 具体描述
建议改成“现代数据库足够强大 可以**通过扩展**处理大量数据”

**Comment by yifangwang08** [comment]
感谢反馈！
