### ISSUE TITLE
业务方向 - 用 Tableau 创建可视化（二选一）-课程3—7.练习：连接数据

### ISSUE THREAD

**Issue by wushu6336** [udacity/band-issues-cn#207]
## 截图
<img width="1212" alt="demo" src=
![_20181216210504](https://user-images.githubusercontent.com/35553899/50053829-4c563e80-0176-11e9-9940-cdd7b3dc07c7.png)

">

## 具体描述
“回报表”建议改为“退货表”，后续的returns表也建议修改

**Comment by yifangwang08** [comment]
感谢反馈！
