### ISSUE TITLE
商业数据分析 II > 如果我只想用一个数字呢？

### ISSUE THREAD

**Issue by Xiankai-Wan** [udacity/band-issues-cn#21]
## 课程导航+地址
商业数据分析 II > [如果我只想用一个数字呢？](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/e37a7e2f-d479-4962-a366-cdcdf8aee7f6/modules/172d7273-794a-498c-a908-6803cfc7d6b6/lessons/ff38bd12-68b6-4ae9-971e-bbefe991a201/concepts/61e1da64-6ca0-41e1-825c-28e71a91471f)

## 截图
![image](https://user-images.githubusercontent.com/25104361/43836019-8d402406-9b46-11e8-93ca-3338f49af68a.png)

## 具体描述
range 都是统一翻译为 值域 的，这里应该是值域。

**Comment by evestorm** [comment]
需改为“极差”

**Comment by Xiankai-Wan** [comment]
课程好几处值域和极差的概念和说明在混用，建议要么统一为一个，要么就在前面的文字部分做一个说明，这样避免学员弄混。
