### ISSUE TITLE
业务方向 - 用 Tableau 创建可视化（二选一）- 课程3 - 13. 文本：工作表

### ISSUE THREAD

**Issue by wushu6336** [udacity/band-issues-cn#211]
## 课程导航+地址
业务方向 - 用 Tableau 创建可视化（二选一） > 课程3 >13. 文本：工作表(https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/6ae40236-0ca9-4ee2-80b7-ad715049a9ea/concepts/7cea5ffc-3ea2-4ab4-887f-3d38442d1bc5)

## 截图
<img width="1212" alt="demo" src="
![_20181216205714](https://user-images.githubusercontent.com/35553899/50053739-35fbb300-0175-11e9-9a9f-bd698ec58b37.png)

">

## 具体描述
“分类，定性和时间数据被列为维度。定量数值数据被列为度量。” 这里的翻译比较难理解

**Comment by yifangwang08** [comment]
感谢反馈！
