### ISSUE TITLE
文本错别字

### ISSUE THREAD

**Issue by ketra21** [udacity/band-issues-cn#213]
## 课程导航+地址
例子：商业数据分析 > SQL > SQL JOIN > [15. 文本：其他JOIN注意事项](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/fb1232d2-1cfe-4bb0-8d6f-7bab75e9796c/modules/633ca2b0-b1b2-4821-89f8-60584b2a4a54/lessons/8f23fc69-7c88-4a94-97a4-d5f6ef51cf7b/concepts/1f196edd-3923-4db2-a509-040be4ac3210)

## 截图
<img width="1212" alt="demo" src="图片地址
![image](https://user-images.githubusercontent.com/38323732/50054659-3dc05500-017f-11e9-9302-66bc9e4ffbab.png)
">

## 具体描述
消费时间——————>浪费时间

**Comment by yifangwang08** [comment]
感谢反馈！
