### ISSUE TITLE
推论统计学 - Lesson 3 基础知识4 - 正态分布2 - Concept 14 Karma 练习部分

### ISSUE THREAD

**Issue by Hty9103** [udacity/band-issues-cn#224]
这个concept里的视频有提到不知指向的视频，但是该视频本身不难理解。Kylie看下是否需要做调整。

**Comment by Hty9103** [comment]
Concept 15-20 都是Karma 练习。

**Comment by Hty9103** [comment]
当concept 15 里的视频给出均值和标准差之后，concept 16 及以后的练习就可以用这个章节所学知识来做了，倒是不难。

**Comment by Kyliewang** [comment]
补充提示，可以使用 excel 计算标准差的方式来计算。
