### ISSUE TITLE
描述统计学 II > 12 最后要点

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#32]
## 课程导航+地址
描述统计学 II > [12 最后要点](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/e37a7e2f-d479-4962-a366-cdcdf8aee7f6/modules/172d7273-794a-498c-a908-6803cfc7d6b6/lessons/ff38bd12-68b6-4ae9-971e-bbefe991a201/concepts/4cc145a1-c4d7-4bc3-b83b-27bb66846df4)

## 截图
![screen shot 2018-08-08 at 9 54 05 pm](https://user-images.githubusercontent.com/6949550/43841735-6d2b9096-9b56-11e8-8991-1809eade665e.png)

## 具体描述
这句翻译为“意味着”好像比原文（相关联）程度更高，感觉不太合适。

**Comment by evestorm** [comment]
不影响信息传达的准确性
