### ISSUE TITLE
描述统计学2 > 集中趋势和离散程度测量总结

### ISSUE THREAD

**Issue by baizhenhui** [udacity/band-issues-cn#38]
## 截图
![image](https://user-images.githubusercontent.com/36567451/43844809-1ef1cb82-9b5d-11e8-8043-e755cd1f154a.png)

## 具体描述
这样的描述很令人疑惑。我认为，可以不深入讨论，但是要标注清楚。建议：

样本方差的计算公式为：
![image](https://user-images.githubusercontent.com/36567451/43845191-006a6d6c-9b5e-11e8-91ad-767252325d03.png)

总体方差的计算公式为：
![image](https://user-images.githubusercontent.com/36567451/43845162-ee9a8162-9b5d-11e8-9abf-293ba7166f8a.png)
为什么在计算样本方差时要除以(n-1)而不是n，可以[在此](https://stats.stackexchange.com/questions/3931/intuitive-explanation-for-dividing-by-n-1-when-calculating-standard-deviation) 找到解释。

**Comment by evestorm** [comment]
Awesome!
