### ISSUE TITLE
用数据分析解决问题 > 分析问题框架 > 5. 数据准备

### ISSUE THREAD

**Issue by molock** [udacity/band-issues-cn#5]
## 课程导航+地址
3. 用数据分析解决问题 > 分析问题框架 > [5. 数据准备](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/23f15771-2196-4410-90b8-6661c3694682/modules/8f120816-9158-4429-8c7d-032a66dc6b22/lessons/dd7bf461-dfec-484c-b932-d09744913c98/concepts/1885d3d4-1052-41d3-b632-9c3eac5aea5f)

## 截图
![123](https://i.loli.net/2018/08/06/5b685e6f95e82.png)

## 具体描述
视频1:05s处字幕"取样"，应断句到上一行字幕”最后 你可能需要对数据集“的最后

**Comment by evestorm** [comment]
@molock 下次截图不需要放在自己的图库呢，直接用QQ或微信截图后在此处快捷键粘贴就能上传啦~
