### ISSUE TITLE
用数据分析解决问题 > 预测商业决策带来的收益增长 > 4. 项目验证

### ISSUE THREAD

**Issue by molock** [udacity/band-issues-cn#58]
## 课程导航+地址
用数据分析解决问题 > 预测商业决策带来的收益增长 > [4. 项目验证](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/23f15771-2196-4410-90b8-6661c3694682/modules/undefined/lessons/ecaae2f7-715a-4595-8052-ba6e6b98a4cc/concepts/771d1f65-15de-4727-b102-e9290b9a98a0)

## 截图
<img width="1212" alt="demo" src="https://i.loli.net/2018/08/10/5b6d9dc070c63.png">

## 具体描述
截图红色方框内的文字：“**在提交前**，请检查你对以下问题的答案，看看你是否采取的是计算总体利润的正确流程。”
比较不符合汉语习惯，而且就算能成功答出以下问题，计算总体利润的过程也不一定正确，因此可以加上“初步验证”的限定文字。

整句话可优化如下：“**在提交前**，请检查是否能给出以下问题的正确答案，用以初步验证你计算整体利润的流程是否正确。”

**Comment by evestorm** [comment]
Awesome!
