### ISSUE TITLE
电子表格2： 处理数据 > 练习：拆分列

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#59]
## 课程导航+地址
电子表格2： 处理数据 > [练习：拆分列](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/e37a7e2f-d479-4962-a366-cdcdf8aee7f6/modules/172d7273-794a-498c-a908-6803cfc7d6b6/lessons/b829e504-fe21-4900-a223-9356d479e545/concepts/81c9bccf-fbfb-44ef-940e-ae225725a90f)

## 截图

截图一
<img width="1318" alt="screen shot 2018-08-11 at 9 43 07 am" src="https://user-images.githubusercontent.com/6949550/43986885-3e2fa830-9d4b-11e8-99d9-8b43cbea0a1e.png">

截图二
<img width="1314" alt="screen shot 2018-08-11 at 10 22 00 am" src="https://user-images.githubusercontent.com/6949550/43987255-9f620468-9d50-11e8-9e0f-66fd99d848c1.png">

## 具体描述
高亮地方的“美国联盟棒球”可能翻为“美国棒球联盟”更通顺一些？或许指的是 [美国职业棒球大联盟](https://zh.wikipedia.org/zh-cn/%E7%BE%8E%E5%9C%8B%E8%81%B7%E6%A5%AD%E6%A3%92%E7%90%83%E5%A4%A7%E8%81%AF%E7%9B%9F)。

补充，看了后面内容后发现，也是“美国棒球联盟”（截图二）。

**Comment by evestorm** [comment]
眼尖~
