### ISSUE TITLE
描述统计学 I > 26 练习 均值表达式

### ISSUE THREAD

**Issue by Xiankai-Wan** [udacity/band-issues-cn#6]
## 课程导航+地址
描述统计学 I > [26 练习 均值表达式](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/e37a7e2f-d479-4962-a366-cdcdf8aee7f6/modules/172d7273-794a-498c-a908-6803cfc7d6b6/lessons/7c28a383-f50b-4a62-bbc1-fa6b2b52504a/concepts/57bd8dde-9b68-41e7-82be-4ac7e70e4205)

## 截图
![image](https://user-images.githubusercontent.com/25104361/43723788-1257169a-99cb-11e8-8c10-79aeed2734b0.png)

## 具体描述
这里B选项少了除法的横线，具体可以参考E选项。

**Comment by evestorm** [comment]
公式没问题，目前来看，发现浏览器放大到120%就能显示出来了。所以我将公式的font-size设置为了120%解决了此问题，希望 @Xiankai-Wan  能再帮忙测试下，你这边OK了没
