### ISSUE TITLE
数据处理>8.项目描述

### ISSUE THREAD

**Issue by KamikidFu** [udacity/band-issues-cn#62]
## 课程导航+地址
1.欢迎来到纳米学位！>数据处理>[8.项目描述](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/2b23e28b-275e-473f-862f-575b002afdb0/modules/22b3ae26-a35c-46f2-94dd-a3a846d179a4/lessons/07b383df-b9dd-4e67-9baa-cbe1a4107bbf/concepts/cfe8c3aa-b5c3-4d99-bbbc-4a8c751debf3#)

## 截图
![1](https://user-images.githubusercontent.com/25498506/43989272-01136a68-9d9b-11e8-832d-6818f0464aaf.png)

## 具体描述
关于PC如何屏幕截图的链接指向YouTube视频，属于墙外链接。

**Comment by Kyliewang** [comment]
谢谢~
