### ISSUE TITLE
电子表格2: 处理数据 > 练习：提取文本

### ISSUE THREAD

**Issue by Xiankai-Wan** [udacity/band-issues-cn#63]
## 课程导航+地址
电子表格2: 处理数据 > [练习：提取文本](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/e37a7e2f-d479-4962-a366-cdcdf8aee7f6/modules/172d7273-794a-498c-a908-6803cfc7d6b6/lessons/b829e504-fe21-4900-a223-9356d479e545/concepts/5637903a-2645-48a6-a8ea-987aa426a600)

## 截图
![image](https://user-images.githubusercontent.com/25104361/44000010-8ef03884-9e4a-11e8-8623-0a46ec840584.png)

## 具体描述
MD语法没有显示出来，这里应该是想要使用斜体吧，需要和前面的文字有一个空格才对， 应该是 _其后_

**Comment by sylviasun916** [comment]
fixed and thanks!
