### ISSUE TITLE
电子表格2： 处理数据 > 练习：提取文本

### ISSUE THREAD

**Issue by PoBlue** [udacity/band-issues-cn#64]
## 课程导航+地址
[电子表格2： 处理数据 > 练习：提取文本](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/e37a7e2f-d479-4962-a366-cdcdf8aee7f6/modules/172d7273-794a-498c-a908-6803cfc7d6b6/lessons/b829e504-fe21-4900-a223-9356d479e545/concepts/5637903a-2645-48a6-a8ea-987aa426a600)

## 截图
<img width="671" alt="2018-08-12 8 41 17" src="https://user-images.githubusercontent.com/9304701/44002095-1988b9f6-9e70-11e8-8f84-e38047eaad29.png">

## 具体描述
“你想让 MID 函数从文本返回的字符数”

应改为：“你希望 MID 从文本中返回字符的个数”

参考 [Excel 文档](https://support.office.com/zh-cn/article/mid%E3%80%81midb-%E5%87%BD%E6%95%B0-d5f9e25c-d7d6-472e-b568-4ecb12433028) , 觉得它的翻译更加容易理解些

**Comment by sylviasun916** [comment]
已修改感谢反馈！
