### ISSUE TITLE
电子表格2： 处理数据 > 练习：提取文本

### ISSUE THREAD

**Issue by PoBlue** [udacity/band-issues-cn#65]
## 课程导航+地址
[电子表格2： 处理数据 > 练习：提取文本](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/e37a7e2f-d479-4962-a366-cdcdf8aee7f6/modules/172d7273-794a-498c-a908-6803cfc7d6b6/lessons/b829e504-fe21-4900-a223-9356d479e545/concepts/5637903a-2645-48a6-a8ea-987aa426a600)

## 截图
<img width="852" alt="2018-08-12 8 46 08" src="https://user-images.githubusercontent.com/9304701/44002140-d736b516-9e70-11e8-8005-2e19ecf801ae.png">

## 具体描述
“字符数” 改为 "字符个数" 会比较好理解些

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
