### ISSUE TITLE
电子表格2： 处理数据 > 数学函数

### ISSUE THREAD

**Issue by PoBlue** [udacity/band-issues-cn#66]
## 课程导航+地址
[电子表格2： 处理数据 > 数学函数](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/e37a7e2f-d479-4962-a366-cdcdf8aee7f6/modules/172d7273-794a-498c-a908-6803cfc7d6b6/lessons/b829e504-fe21-4900-a223-9356d479e545/concepts/927d63f8-5f85-4fd7-b7c4-56f0bf779daa)

## 截图
<img width="842" alt="2018-08-12 8 55 38" src="https://user-images.githubusercontent.com/9304701/44002227-312c0318-9e72-11e8-8ae9-dfe091f8996c.png">

## 具体描述
视频01:10处 

字幕：“确定一个求和区域更简单” 

应改为：“确定一个区域进行求和 更简单”

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
