### ISSUE TITLE
电子表格2： 处理数据 > 重复行

### ISSUE THREAD

**Issue by PoBlue** [udacity/band-issues-cn#67]
## 课程导航+地址
[电子表格2： 处理数据 > 重复行](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/e37a7e2f-d479-4962-a366-cdcdf8aee7f6/modules/172d7273-794a-498c-a908-6803cfc7d6b6/lessons/b829e504-fe21-4900-a223-9356d479e545/concepts/1c661b03-a6b8-4bce-a64a-569998072a26)

## 截图
<img width="829" alt="2018-08-12 9 08 28" src="https://user-images.githubusercontent.com/9304701/44002372-087b4bd4-9e74-11e8-916e-9b2b2347c999.png">

## 具体描述
视频00:12处 

字幕：“但并非是整洁的数据” 

应改为：“但并非是我们所指的整洁的数据”

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
