### ISSUE TITLE
电子表格2： 处理数据 > 重复行

### ISSUE THREAD

**Issue by PoBlue** [udacity/band-issues-cn#68]
## 课程导航+地址
[电子表格2： 处理数据 > 重复行](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/e37a7e2f-d479-4962-a366-cdcdf8aee7f6/modules/172d7273-794a-498c-a908-6803cfc7d6b6/lessons/b829e504-fe21-4900-a223-9356d479e545/concepts/1c661b03-a6b8-4bce-a64a-569998072a26)

## 截图
<img width="809" alt="2018-08-12 9 16 06" src="https://user-images.githubusercontent.com/9304701/44002439-f4406ffe-9e74-11e8-8afa-ed6ed770e1b8.png">

## 具体描述
视频后面的语音和画面不同步，所讲的是之前的画面～

**Comment by Kyliewang** [comment]
@sylviasun916 时间轴问题，辛苦圆圆评估一下哦~

**Comment by sylviasun916** [comment]
fixed and thanks
