### ISSUE TITLE
电子表格2： 处理数据 > 拆分列

### ISSUE THREAD

**Issue by PoBlue** [udacity/band-issues-cn#69]
## 课程导航+地址
[电子表格2： 处理数据 > 拆分列](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/e37a7e2f-d479-4962-a366-cdcdf8aee7f6/modules/172d7273-794a-498c-a908-6803cfc7d6b6/lessons/b829e504-fe21-4900-a223-9356d479e545/concepts/5c21af15-ef12-439c-a849-1346c5291c16)

## 截图
<img width="843" alt="2018-08-12 9 23 29" src="https://user-images.githubusercontent.com/9304701/44002534-d21647d0-9e76-11e8-9342-e28c53dd5278.png">

## 具体描述
视频00:05处

字幕：“拆分结合到一个单元格中的数据”

应改为：“拆分那些结合到一个单元格中的数据”

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
