### ISSUE TITLE
解读数据可视化

### ISSUE THREAD

**Issue by baizhenhui** [udacity/band-issues-cn#7]
## 截图
![image](https://user-images.githubusercontent.com/36567451/43723751-f66c094a-99ca-11e8-9a04-017ab8bab19b.png)

## 具体描述
点击此处链接跳转到优达登录页面，反复输入账号密码都登录不上去。

**Comment by evestorm** [comment]
已替换为正确的论坛地址。但该测试账号无法访问论坛，请谅解。
