### ISSUE TITLE
电子表格3: 分析数据 > 练习：VLOOKUP函数

### ISSUE THREAD

**Issue by Xiankai-Wan** [udacity/band-issues-cn#70]
## 课程导航+地址
电子表格3: 分析数据 > [练习：VLOOKUP函数](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/e37a7e2f-d479-4962-a366-cdcdf8aee7f6/modules/172d7273-794a-498c-a908-6803cfc7d6b6/lessons/92407fe0-857f-40de-a1c5-b232336d9e75/concepts/2e693ab4-efd6-4d46-809e-70a342beb5b8)

## 截图
![image](https://user-images.githubusercontent.com/25104361/44002560-2c1ffda2-9e77-11e8-8fba-94f329450e66.png)

## 具体描述
这里重复值应该是41个，而不是答案所设置的42个，这里应该是错将去重显示的数字当作了最后的结果。

**Comment by Kyliewang** [comment]
已经修改。
