### ISSUE TITLE
电子表格2： 处理数据 > 拆分列

### ISSUE THREAD

**Issue by PoBlue** [udacity/band-issues-cn#71]
## 课程导航+地址
[电子表格2： 处理数据 > 拆分列](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/e37a7e2f-d479-4962-a366-cdcdf8aee7f6/modules/172d7273-794a-498c-a908-6803cfc7d6b6/lessons/b829e504-fe21-4900-a223-9356d479e545/concepts/5c21af15-ef12-439c-a849-1346c5291c16)

## 截图
<img width="831" alt="2018-08-12 9 35 08" src="https://user-images.githubusercontent.com/9304701/44002585-9a31fc28-9e77-11e8-946d-93baf32671c5.png">

## 具体描述
后面音画不同步，所讲的是前 1 ，2 秒的画面

**Comment by Kyliewang** [comment]
可能是时间轴，辛苦圆圆看一下~ @sylviasun916

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
