### ISSUE TITLE
电子表格3： 分析数据 > 简介

### ISSUE THREAD

**Issue by PoBlue** [udacity/band-issues-cn#72]
## 课程导航+地址
[电子表格3： 分析数据 > 简介](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/e37a7e2f-d479-4962-a366-cdcdf8aee7f6/modules/172d7273-794a-498c-a908-6803cfc7d6b6/lessons/92407fe0-857f-40de-a1c5-b232336d9e75/concepts/3b64b282-5fdd-47d5-a17b-db06c1d0770b)

## 截图
<img width="829" alt="2018-08-12 9 59 18" src="https://user-images.githubusercontent.com/9304701/44002791-2f53cdba-9e7b-11e8-9a5f-0210eacf62bb.png">
<img width="827" alt="2018-08-12 9 59 25" src="https://user-images.githubusercontent.com/9304701/44002796-3af40a9a-9e7b-11e8-8b1c-8d0781b759fd.png">

## 具体描述
后面她来一句 `"例如，xxx 要简单的多"`，有点容易误解为 xxx 更简单。。。

建议：

视频 02:10 处:  “记住 student roster 比一些奇怪的地址”
视频 02:11 处：“例如 sheet3!A1:J943 要简单的多”

改为：

视频 02:10 处:  “记住 student roster”
视频 02:11 处：“比一些奇怪的地址 例如 sheet3!A1:J943 要简单的多”

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
