### ISSUE TITLE
电子表格3： 分析数据 > 简介

### ISSUE THREAD

**Issue by PoBlue** [udacity/band-issues-cn#73]
## 课程导航+地址
[电子表格3： 分析数据 > 简介](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/e37a7e2f-d479-4962-a366-cdcdf8aee7f6/modules/172d7273-794a-498c-a908-6803cfc7d6b6/lessons/92407fe0-857f-40de-a1c5-b232336d9e75/concepts/3b64b282-5fdd-47d5-a17b-db06c1d0770b)

## 截图
<img width="843" alt="2018-08-12 10 06 54" src="https://user-images.githubusercontent.com/9304701/44002849-1cf5983c-9e7c-11e8-8082-b9b101e58c93.png">

## 具体描述
视频02:24处

字幕：“并在公式变更复杂后更容易理解公式”

应改为：“并且更容易理解变得更加复杂的公式”

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
