### ISSUE TITLE
电子表格3： 分析数据 > 逻辑函数：IF 函数

### ISSUE THREAD

**Issue by PoBlue** [udacity/band-issues-cn#74]
## 课程导航+地址
[电子表格3： 分析数据 > 逻辑函数：IF 函数](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/e37a7e2f-d479-4962-a366-cdcdf8aee7f6/modules/172d7273-794a-498c-a908-6803cfc7d6b6/lessons/92407fe0-857f-40de-a1c5-b232336d9e75/concepts/f75e8c17-83b0-4a45-ab7f-5ebc9dcc2160)

## 截图
<img width="847" alt="2018-08-12 10 26 46" src="https://user-images.githubusercontent.com/9304701/44003056-036d5870-9e7f-11e8-8c8c-2640f1757503.png">

## 具体描述
视频01:28处

字幕：`针对条件为假时 "Oranges Rock`

应改为：`针对条件为假时 输出为 "Oranges Rock"`

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
