### ISSUE TITLE
电子表格 4:可视化数据 > 10 直方图

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#75]
## 课程导航+地址
电子表格 4:可视化数据 > [10 直方图](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/e37a7e2f-d479-4962-a366-cdcdf8aee7f6/modules/172d7273-794a-498c-a908-6803cfc7d6b6/lessons/a5450c84-d583-4c69-9f33-b11aeacc53ee/concepts/3efb9556-6821-4dec-83be-58ae20efd800)

## 截图

截图一
![screen shot 2018-08-13 at 11 11 22 am](https://user-images.githubusercontent.com/6949550/44011650-6779bc38-9eec-11e8-9397-7ce7add21b5a.png)

截图二
<img width="1219" alt="screen shot 2018-08-13 at 11 06 36 am" src="https://user-images.githubusercontent.com/6949550/44011659-714f1f50-9eec-11e8-81dd-1b9adbd4282c.png">

## 具体描述

现在 Mac 下的 Excel 也可以在 Data 菜单里找到 Data Analysis 工具（截图二）。

**Comment by Kyliewang** [comment]
感谢提出，但是优先级并不是很高，目前暂时先不处理哦~
