### ISSUE TITLE
电子表格 4:可视化数据 > 10 直方图

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#76]
## 课程导航+地址
电子表格 4:可视化数据 > [10 直方图](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/e37a7e2f-d479-4962-a366-cdcdf8aee7f6/modules/172d7273-794a-498c-a908-6803cfc7d6b6/lessons/a5450c84-d583-4c69-9f33-b11aeacc53ee/concepts/3efb9556-6821-4dec-83be-58ae20efd800)

## 截图

截图一
![screen shot 2018-08-13 at 11 24 01 am](https://user-images.githubusercontent.com/6949550/44011714-b9ef12ce-9eec-11e8-937e-c08f20fa0e43.png)

截图二
<img width="1252" alt="screen shot 2018-08-13 at 11 23 44 am" src="https://user-images.githubusercontent.com/6949550/44011768-fb81ca2e-9eec-11e8-8965-f0430d7d63b3.png">

## 具体描述

第二种建直方图的方法在 Mac 下也可以了（截图二）。

**Comment by Kyliewang** [comment]
已经补充注释说明，感谢提出！
