### ISSUE TITLE
用数据分析解决问题 > 分析问题解决框架 > 5 数据准备

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#77]
## 课程导航+地址
用数据分析解决问题 > 分析问题解决框架 > [5 数据准备](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/23f15771-2196-4410-90b8-6661c3694682/modules/8f120816-9158-4429-8c7d-032a66dc6b22/lessons/dd7bf461-dfec-484c-b932-d09744913c98/concepts/1885d3d4-1052-41d3-b632-9c3eac5aea5f)

## 截图
![screen shot 2018-08-13 at 3 40 40 pm](https://user-images.githubusercontent.com/6949550/44018712-4046ee9c-9f0f-11e8-89f1-7bc9d4799065.png)

## 具体描述
高亮那句话好像并没有在 [Data preparation - Wikipedia](https://en.wikipedia.org/wiki/Data_preparation) 找到呢，不知是不是我没找到对应的词条。如果给出维基百科的引用链接就更好啦。

还有，前面两课里的 “业务理解”、“数据理解”，也没找到对应的维基百科词条，但都注明了引用自维基百科。在词条 [Cross-industry standard process for data mining - Wikipedia](https://en.wikipedia.org/wiki/Cross-industry_standard_process_for_data_mining)  里也没看到类似描述。

**Comment by Kyliewang** [comment]
数据准备应当对应的词条为 - data wrangling： https://en.wikipedia.org/wiki/Data_wrangling
