### ISSUE TITLE
项目：分析问卷数据 > 项目概述

### ISSUE THREAD

**Issue by Xiankai-Wan** [udacity/band-issues-cn#78]
## 课程导航+地址
项目：分析问卷数据 > [项目概述](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/e37a7e2f-d479-4962-a366-cdcdf8aee7f6/modules/172d7273-794a-498c-a908-6803cfc7d6b6/lessons/6001b33e-f552-4729-ac5a-6943cfec7537/concepts/764907fe-137d-4738-b691-b55474837624)

## 截图
![image](https://user-images.githubusercontent.com/25104361/44065528-cfbcff06-9f9d-11e8-8695-28cc744f3aff.png)

## 具体描述
第一个链接，打开显示调查是private，根本查看不到任何有用的信息。第二个项目链接，下载的是整个商业数据分析的三个项目zip文件，如果后面课程结构和项目有变化的话，这里最好是只提供这个项目的文件即可。

**Comment by Kyliewang** [comment]
感谢反馈~ 已经修改！
