### ISSUE TITLE
描述统计学 I  > 17 表达式是什么？

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#8]
## 课程导航+地址
描述统计学 I  > [17 表达式是什么？](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/e37a7e2f-d479-4962-a366-cdcdf8aee7f6/modules/172d7273-794a-498c-a908-6803cfc7d6b6/lessons/7c28a383-f50b-4a62-bbc1-fa6b2b52504a/concepts/25b5e8b7-17f7-428e-a55b-a6a53fc11cf4)

## 截图

![screen shot 2018-08-06 at 11 14 30 pm](https://user-images.githubusercontent.com/6949550/43725364-e9224b24-99ce-11e8-8a9e-6933a88b5b22.png)

## 具体描述

Markdown 有序列表好像有点问题。

**Comment by evestorm** [comment]
fixed!
