### ISSUE TITLE
用数据分析解决问题 > 线性回归 > 7 Google 表格中的线性方程

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#80]
## 课程导航+地址
用数据分析解决问题 > 线性回归 >[ 7 Google 表格中的线性方程](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/23f15771-2196-4410-90b8-6661c3694682/modules/51c76090-9346-4506-8f01-bfae811dcc94/lessons/316c6f13-a660-456e-86a6-bbae79f8c577/concepts/4ee5cae6-f49d-4e86-8aa8-d1ee48477345)

## 截图
![screen shot 2018-08-22 at 12 22 19 pm](https://user-images.githubusercontent.com/6949550/44501517-17524780-a6c0-11e8-8137-9a3f7f339b0e.png)

## 具体描述
箭头标记的地方不确定是不是 Markdown 语法有点小问题。

**Comment by sylviasun916** [comment]
fixed and thanks!
