### ISSUE TITLE
用数据分析解决问题 > 线性回归 > 15 线性回归与分类变量

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#81]
## 课程导航+地址
用数据分析解决问题 > 线性回归 > [15 线性回归与分类变量](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/23f15771-2196-4410-90b8-6661c3694682/modules/51c76090-9346-4506-8f01-bfae811dcc94/lessons/316c6f13-a660-456e-86a6-bbae79f8c577/concepts/e4ce950e-b079-4e7b-9898-62b1f4ec14cf)

## 截图
![screen shot 2018-08-23 at 5 43 11 pm](https://user-images.githubusercontent.com/6949550/44518136-14754800-a6fc-11e8-9920-eccbbf91f541.png)

## 具体描述
两个红框里的文字一模一样，不知是不是有意的。

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
