### ISSUE TITLE
SQL 基础 -> 基本 SQL -> 17 解决方案：LIMIT

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#83]
## 课程导航+地址
SQL 基础 -> 基本 SQL -> [17 解决方案：LIMIT](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/5dedcb7b-7b19-4ef3-b19b-e7b555c75807/modules/55808a74-9b29-4fc2-b25a-0b1ca19038e3/lessons/614cf95a-13bf-406c-b092-e757178e633b/concepts/9fb38d47-1a85-4478-b77f-600a2eb329a6)

## 截图

截图一
![screen shot 2018-08-24 at 4 51 21 pm](https://user-images.githubusercontent.com/6949550/44575229-169fdb00-a7be-11e8-8d4c-371740efee03.png)

截图二
![screen shot 2018-08-24 at 4 52 36 pm](https://user-images.githubusercontent.com/6949550/44575250-25868d80-a7be-11e8-8b5b-5d90229ffab5.png)

## 具体描述
对比之前课程类似的地方（截图二），箭头那里的 Markdown 语法好像有点问题。

**Comment by Kyliewang** [comment]
已修改，谢谢。
