### ISSUE TITLE
sql进阶+[窗口功能1]

### ISSUE THREAD

**Issue by baizhenhui** [udacity/band-issues-cn#84]
## 截图
![image](https://user-images.githubusercontent.com/36567451/44625818-63152300-a944-11e8-85c7-0f894fea864b.png)
![image](https://user-images.githubusercontent.com/36567451/44625823-6d372180-a944-11e8-9130-b4e1f41894cd.png)

## 具体描述
网址错误

**Comment by Kyliewang** [comment]
已修复。
