### ISSUE TITLE
SQL 基础 -> SQL JOIN -> 6 Text: ERD 提醒

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#85]
## 课程导航+地址
SQL 基础 -> SQL JOIN -> [6 Text: ERD 提醒](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/5dedcb7b-7b19-4ef3-b19b-e7b555c75807/modules/55808a74-9b29-4fc2-b25a-0b1ca19038e3/lessons/8f23fc69-7c88-4a94-97a4-d5f6ef51cf7b/concepts/57f82755-506c-4fb5-af0f-312b52ed340e)

## 截图
![screen shot 2018-08-30 at 5 22 01 pm](https://user-images.githubusercontent.com/6949550/44842834-747a6a00-ac79-11e8-9d62-5a0b2459aa52.png)

## 具体描述
没理解错的话，箭头标记的应该是 ERD，不是 RED。

**Comment by sylviasun916** [comment]
已修改，感谢反馈！
