### ISSUE TITLE
SQL 基础 -> SQL JOIN -> 13 视频：其他 JOIN 的目的

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#87]
## 课程导航+地址
SQL 基础 -> SQL JOIN ->[ 13 视频：其他 JOIN 的目的](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/5dedcb7b-7b19-4ef3-b19b-e7b555c75807/modules/55808a74-9b29-4fc2-b25a-0b1ca19038e3/lessons/8f23fc69-7c88-4a94-97a4-d5f6ef51cf7b/concepts/08c5b089-9606-4cdd-9ca4-d12f5d04b425)

## 截图
![screen shot 2018-08-31 at 10 08 32 am](https://user-images.githubusercontent.com/6949550/44888879-f6b07000-ad05-11e8-8e91-5d176db73d54.png)

## 具体描述
“但”应该是“当”？😂

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
