### ISSUE TITLE
数据可视化简介 > 3. 数据可视化的驱动力

### ISSUE THREAD

**Issue by Xiankai-Wan** [udacity/band-issues-cn#88]
## 课程导航+地址
数据可视化简介 > [3. 数据可视化的驱动力](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/ce38115a-28de-47a2-8ced-eb37bb2a39f3/concepts/1a8599fc-c307-432e-859d-eaca8e4e47d8)

## 截图
![image](https://user-images.githubusercontent.com/25104361/44942823-c7c0f980-adec-11e8-96b6-95420c1be581.png)

## 具体描述
Google sheet的外链，国内学员无法访问，可以提供csv文件下载链接。

**Comment by Kyliewang** [comment]
已经替换为墙内链接。
