### ISSUE TITLE
数据可视化简介 > 7. 单变量图形

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#89]
## 课程导航+地址
数据可视化简介 >[ 7. 单变量图形](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/ce38115a-28de-47a2-8ced-eb37bb2a39f3/concepts/67e37af2-54ee-4b52-aeda-763341b9879a)

## 截图
![screen shot 2018-09-01 at 4 57 18 pm](https://user-images.githubusercontent.com/6949550/44944380-4ecf9b00-ae08-11e8-8b55-25b5586135e6.png)

## 具体描述
中文字幕看起来应该是“列”而不是“行”。

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
