### ISSUE TITLE
用数据分析解决问题 > 分析问题解决框架 > [4. 数据理解]

### ISSUE THREAD

**Issue by molock** [udacity/band-issues-cn#9]
## 课程导航+地址
用数据分析解决问题 > 分析问题解决框架 > [4. 数据理解](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/23f15771-2196-4410-90b8-6661c3694682/modules/8f120816-9158-4429-8c7d-032a66dc6b22/lessons/dd7bf461-dfec-484c-b932-d09744913c98/concepts/b032e6ce-b1c5-4694-9e0b-7c059dc11104)

## 截图
<img width="1212" alt="demo" src="https://i.loli.net/2018/08/06/5b686996b80d1.png">

## 具体描述
视频1 : 09s处字幕"此外 对数据的可靠理解"，建议改为”此外 对数据的深刻理解“， 更符合汉语的使用习惯

**Comment by evestorm** [comment]
赞！已优化
