### ISSUE TITLE
数据可视化简介 > 10 散点图练习

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#90]
## 课程导航+地址
数据可视化简介 >[ 10 散点图练习](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/ce38115a-28de-47a2-8ced-eb37bb2a39f3/concepts/48aaa004-f7ea-4ce8-ad73-bcbb291d3875)

## 截图

![screen shot 2018-09-01 at 5 28 38 pm](https://user-images.githubusercontent.com/6949550/44944614-8f311800-ae0c-11e8-806e-8ad94471b42d.png)
![screen shot 2018-09-01 at 5 28 44 pm](https://user-images.githubusercontent.com/6949550/44944615-8fc9ae80-ae0c-11e8-9372-903fa7c159ad.png)

## 具体描述
练习题最上面的 [数据链接](https://github.com/udacity/new-dand-basic-china/blob/master/Ab%20Test/%E5%9B%9E%E5%BD%92/%E6%95%A3%E7%82%B9%E5%9B%BE%E7%BB%83%E4%B9%A0%E6%95%B0%E6%8D%AE.xlsx?raw=true) 不需要翻墙，后面两个是 Google docs 的链接。不知是不是也需要保持一致。

**Comment by Kyliewang** [comment]
已经替换，感谢反馈！
