### ISSUE TITLE
数据可视化 -> [复习]

### ISSUE THREAD

**Issue by baizhenhui** [udacity/band-issues-cn#92]
## 课程导航+地址
例子：数据可视化 -> [复习](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/ce38115a-28de-47a2-8ced-eb37bb2a39f3/concepts/2ede00e2-0575-4cd8-bd6e-64026bac0290)
## 截图
![image](https://user-images.githubusercontent.com/36567451/44946683-5c4e4a80-ae33-11e8-8e0b-7922fb3d32af.png)

## 具体描述
翻译错误，`安全`改为`完全`，去掉`比较`。

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
