### ISSUE TITLE
设计 -> 2. 课程概述

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#95]
## 课程导航+地址
设计 -> [2. 课程概述](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/3170e950-5743-4dbb-875f-6da4a3ed30f1/concepts/d2e6d557-e64a-4a71-a8d8-5acb154e6d7f)

## 截图
![screen shot 2018-09-02 at 4 27 28 pm](https://user-images.githubusercontent.com/6949550/44953908-278ed180-aecd-11e8-987d-e0e4d1273036.png)

## 具体描述
箭头处缺少链接。

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
