### ISSUE TITLE
设计 -> 3. 探索性与解释性分析

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#96]
## 课程导航+地址
设计 -> [3. 探索性与解释性分析](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/3170e950-5743-4dbb-875f-6da4a3ed30f1/concepts/87aa9106-ba97-412c-b092-a485f879a9fa)

## 截图
![screen shot 2018-09-02 at 4 44 27 pm](https://user-images.githubusercontent.com/6949550/44954049-cb797c80-aecf-11e8-8be7-ca18373d817e.png)

## 具体描述
不知这几行相同的内容是不是有点问题。

**Comment by Kyliewang** [comment]
已经进行翻译优化~ 感谢反馈！
