### ISSUE TITLE
设计 -> 6. 可视化编码的专家之言

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#97]
## 课程导航+地址
设计 -> [6. 可视化编码的专家之言](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/3170e950-5743-4dbb-875f-6da4a3ed30f1/concepts/1a7c9ee5-41b1-43ad-ae15-18154e5151da)

## 截图
![screen shot 2018-09-02 at 5 22 10 pm](https://user-images.githubusercontent.com/6949550/44954467-48f3bb80-aed5-11e8-9f1e-066381a20a64.png)

## 具体描述
- “常被用于散布图表达额外的变量编码 随后的页面将探讨这一点” 这句话中间的空格似乎应该换成其它标点符号。
- 文字内容里的圆括号似乎都是用的半角，感觉应该用中文的全角。:)

**Comment by Kyliewang** [comment]
已经修改，感谢反馈！
