### ISSUE TITLE
设计 -> 11. 不良可视化练习 (第二部分)

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#98]
## 课程导航+地址
设计 -> [11. 不良可视化练习 (第二部分)](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/3170e950-5743-4dbb-875f-6da4a3ed30f1/concepts/0803c6df-1268-499b-8b9e-63ab4f82ccfa)

## 截图
![screen shot 2018-09-02 at 5 43 06 pm](https://user-images.githubusercontent.com/6949550/44954660-c5879980-aed7-11e8-97e8-168beb6979f1.png)

## 具体描述
Markdown 语法有点问题。

**Comment by sylviasun916** [comment]
fixed and thanks!
