### ISSUE TITLE
设计 -> 14. 针对色盲的设计

### ISSUE THREAD

**Issue by jojojojoe** [udacity/band-issues-cn#99]
## 课程导航+地址
设计 -> [14. 针对色盲的设计](https://classroom.udacity.com/nanodegrees/nd100-cn/parts/202d4d7c-f299-424b-a609-8207701da6ea/modules/2841279d-de8d-42ea-bd97-807881170b42/lessons/3170e950-5743-4dbb-875f-6da4a3ed30f1/concepts/e4d4c4d2-2f46-4428-b89c-2f36d1055af8)

## 截图
![screen shot 2018-09-03 at 12 46 42 am](https://user-images.githubusercontent.com/6949550/44958443-f933e500-af12-11e8-80a6-fd43a65f41bc.png)

## 具体描述
Markdown 语法有点问题。

**Comment by sylviasun916** [comment]
fixed and thanks!
